word_dict = {
  "allteftersom": "allt eftersom",
  "alltför": "allt för",
  "alltigenom": "allt igenom",
  "alltihop": "allt ihop",
  "alltmer": "allt mer",
  "alltnog": "allt nog",
  "alltsedan": "allt sedan",
  "densamme": "den samme",
  "dessbättre": "dess bättre",
  "dessförinnan": "dess förinnan",
  "dessvärre": "dess värre",
  "detsamma": "det samma",
  "därvidlag": "där vid lag",
  "förutom": "för utom",
  "förvisso": "för visso",
  "häromdagen": "här om dagen",
  "härvidlag": "här vid lag",
  "ibland": "i bland",
  "ihjäl": "i hjäl",
  "ihop": "i hop",
  "ihåg": "i håg",
  "ingenstans": "ingen stans",
  "isär": "i sär",
  "itu": "i tu",
  "likväl": "lik väl",
  "någonstans": "någon stans",
  "tvärtom": "tvärt om",
  "åsido": "å sido",
  "återigen": "åter igen",
  "överallt": "över allt"
}